title: PyMAA
description: Documentation for the PyMAA package
theme: just-the-docs

url: https://lukasbnordentoft.github.io/PyMAA/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Build settings
markdown: kramdown

compress_html:
  blanklines: true
  
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'